<a href="https://colab.research.google.com/github/othoni-hub/ECG1/blob/main/Ch3_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CPGE-ECG1** 
<img src="https://drive.google.com/uc?id=12Wo3LubGGT4qOvYFAuLP4CyCuwjKNVuk" width="230" height="150" align = "right"/>

## **Ch3 - Notebook : Calcul Matriciel et Résolution de Systèmes**




**O.Thöni - Lycée Saint-Charles Sainte Croix - LE MANS**

# **1. Calcul matriciel en Python natif**

... Pas idéal, mais bon...

Au programme officiel de la classe d'ECG1 ne figurent que les listes Python uni-dimensionnelles, mais on  n'est jamais à l'abri d'un concepteur de sujet n'ayant qu'une idée partielle desdits programmes.

C'est pourquoi nous allons passer quelques minutes pour voir combien cela n'est pas pratique de travailler avec des listes de listes pour modéliser des matrices...

In [ ]:
M = [[0,1,2],[10,11,12]]
M

[[0, 1, 2], [10, 11, 12]]

Voici une "matrice" 2 lignes x 3 colonnes :

In [ ]:
M[1][2] # élément de la 2ème ligne (n°1) et 3ème colonne (n°2)

12

Le nombre de lignes est le nombre de listes que contient la liste principale

In [ ]:
len(M)

2

Le nombre de colonne est le nombre d'éléments de n'importe laquelle des listes éléments de la liste principale

In [ ]:
len(M[0])

3

**Rappelons qu'en Python, les éléments des listes sont numérotés en partant de 0.**

### **1.1 Transposée d'une matrice**

***Idée algorithmique :***

*Pour chaque numéro de ligne i, et chaque numéro de colonne j de A, on affecte à l'élément t<sub>j,i</sub> de la matrice transposée T l'émément  a<sub>i,j</sub> de A.*

In [ ]:
def transposee(A) :
    '''Cette fonction reçoit une matrice rectangulaire et renvoie sa transposée'''

    nb_lignes_A = len(A)
    nb_colonnes_A = len(A[0])

    T = [[ 0 for i in range(nb_lignes_A ) ] for j in range(nb_colonnes_A )]
    
    for i in range(nb_lignes_A) :
        for j in range(nb_colonnes_A) :
            T[j][i] = A[i][j] 
    return T

In [ ]:
transposee(M)

[[0, 10], [1, 11], [2, 12]]

### **1.2 Somme de deux matrices compatibles**

***Idée algorithmique :***

*On teste si les deux matrices ont la même taille, puis, pour chaque numéro de ligne i, et chaque numéro de colonne j de A et B, on affecte l'élément s<sub>i,j</sub> de la matrice somme S avec la somme des éléments a<sub>i,j</sub> et b<sub>i,j</sub>.*

In [ ]:
def somme(A,B) :
    ''' reçoit de matrices A et B, s'assure qu'elles sont compatibles pour la somme et renvoie cette somme.'''
    nb_lignes_A = len(A)
    nb_colonnes_A = len(A[0])
    nb_lignes_B = len(B)
    nb_colonnes_B = len(B[0])

    try :
        assert nb_lignes_A == nb_lignes_B and nb_colonnes_A == nb_colonnes_B
    except :
        print('Matrices non compatibles pour la somme')
    
    S = [[ 0 for j in range(nb_colonnes_A)]for i in range(nb_lignes_A)] 
    for j in range(nb_colonnes_A) :
        for i in range(nb_lignes_A) :
            S[i][j] = A[i][j] + B[i][j]
    return S
    

In [ ]:
M = [[0,1,2],[10,11,12]]
N = [[12,11,10],[2,1,0]]

In [ ]:
somme(M,N)

[[12, 12, 12], [12, 12, 12]]

### **1.3 Produit d'une matrice par un réel**

***Idée algorithmique :***

*Pour chaque numéro de ligne i, et chaque numéro de colonne j de A, on affecte l'élément p<sub>i,j</sub> de la matrice P résultante avec le produit de chaque éléments a<sub>i,j</sub> par le réel Lambda*

In [ ]:
def produit_par_un_reel(Lambda,A) :
    ''' fonction qui reçoit un réel (flottant) et une matrice
    et effectue le produit de la matrice par le réel'''

    nb_lignes_A = len(A)
    nb_colonnes_A = len(A[0])

    P = [[ 0 for j in range(nb_colonnes_A)]for i in range(nb_lignes_A) ]
    for i in range(nb_lignes_A) :
        for j in range(nb_colonnes_A) :
            P[i][j] = Lambda * A[i][j] 
    return P

In [ ]:
produit_par_un_reel(-2,M)

[[0, -2, -4], [-20, -22, -24]]

### **1.4  Produit d'un vecteur ligne par un vecteur colonne de même taille**

***Idée algorithmique :***

*Pour calculer le produit d'un vecteur ligne L par un vecteur colonne C de même taille, on fait la somme, pour chaque indice k, des produits l<sub>0,j</sub> et c<sub>k,0</sub>. (les numérotations commencent à 0...)*

In [ ]:
def ligne_par_colonne(L,C) : 
    '''Fonction qui reçoit un vecteur ligne et un autre vecteur ligne de même taille, le transforme en colonne 
    et renvoie le flottant égal à leur  LxtC'''

    nb_elements = len(L[0])
    
    p = 0
    for k in range(nb_elements) :
        p = p + L[0][k]*C[k][0]

    return p



In [ ]:
 L = [[1,2,3]]
 C = [[4],[5],[6]]
 ligne_par_colonne(L,C)

32

### **1.5 Produit de deux matrices**

In [ ]:
def produit(A,B) :
    '''Cette fonction, après s'être assurée de la compatibilité des deux matrices d'entrée A et B
    pour le produit AxB calcule ce produit'''

    nb_lignes_A = len(A)
    nb_colonnes_A = len(A[0])
    nb_lignes_B = len(B)
    nb_colonnes_B = len(B[0])

    try :
        assert nb_colonnes_A == nb_lignes_B 
    except :
        print('Matrices non compatibles pour le produit')

Vérification des compatibilités :

In [ ]:
M,N

([[0, 1, 2], [10, 11, 12]], [[12, 11, 10], [2, 1, 0]])

In [ ]:
produit(M,N)


Matrices non compatibles pour le produit


In [ ]:
produit(M,transposee(N))

...pas de réaction, produit compatible

***Idée algorithmique :***

*Une fois qu'on a testé si les deux matrices A et B étaient compatibles pour le produit,  pour chaque numéro de ligne i, et chaque numéro de colonne j de A et B, on affecte l'élément p<sub>i,j</sub> de la matrice produit P avec le produit du vecteur ligne n°i de A par le vecteur colonne n°j de B*

In [ ]:
def produit(A,B) :
    '''Cette fonction, après s'être assurée de la compatibilité des deux matrices d'entrée A et B
    pour le produit AxB calcule ce produit'''

    nb_lignes_A = len(A)
    nb_colonnes_A = len(A[0])
    nb_lignes_B = len(B)
    nb_colonnes_B = len(B[0])

    try :
        assert nb_colonnes_A == nb_lignes_B 
    except :
        print('Matrices non compatibles pour le produit')
    
    P = [[ 0 for j in range(nb_colonnes_B)]for i in range(nb_lignes_A)] 
    for i in range(nb_lignes_A) :
        for j in range(nb_colonnes_B) :
            p = 0
            for k in range(nb_colonnes_A) :
                p = p + A[i][k]*B[k][j]
            P[i][j] = p
    return P

In [ ]:
M = [[0,1,2],[10,11,12]]
N = transposee([[12,11,10],[2,1,0]])

In [ ]:
M

[[0, 1, 2], [10, 11, 12]]

In [ ]:
N

[[12, 2], [11, 1], [10, 0]]

In [ ]:
produit(M,N)

[[31, 1], [361, 31]]

In [ ]:
produit(N,M)

[[20, 34, 48], [10, 22, 34], [0, 10, 20]]

... 3 boucles "pour" imbriquées, mais on ne peut pas faire à moins...

ça marche, on est bien content !

---


# **2. Type *array* de *numpy***

NumPy est une bibliothèque Python dédiée au calcul numérique, notamment à la manipulation de matrices et de tableaux.

Elle comporte plusieurs sous-modules qui nous seront également fort utiles ultérieurement.

Elle introduit notamment le type ***numpy.array*** (tableaux), et un certain nombre de fonctions pour calculer sur ce nouveau type.

Sauf indication contraire, **l'intégralité de ce paragraphe est exigible !**


In [ ]:
# import du module numpy sous l'alias np

import numpy as np # On importe le module numpy
                   # On utilisera en préfixe l' "alias" np, pour faire savoir que l'on fait appel
                   # à une fonctionnalité présente dans ce module
                   


La syntaxe pour créer un *np.array* est la suivante : on crée une liste bi-dimensionnelle, et on la convertit en *np.array* :

In [ ]:
M = np.array([[0,1,2],[10,11,12]])
M

array([[ 0,  1,  2],
       [10, 11, 12]])

... D'abord, en cadeau, *numpy* nous dispose ça de manière matricielle !

Mais ce n'est pas tout ! 

Pour les fonctions de base, c'est du gâteau...

## **Accès à un élément particulier :**

In [ ]:
M[0,2] # élément de M, sur la ligne n°0 (donc la 1ère) et la colonne n°2 (donc la 3ème)

2

## **Taille : la fonction *np.shape***

In [ ]:
(nb_lignes , nb_colonnes) = np.shape(M)
(nb_lignes , nb_colonnes)

(2, 3)

## **Transposition : la fonction *np.transpose***

In [ ]:
T = np.transpose(M)
T

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12]])

## **Somme de deux matrices** (compatibles en taille pur la somme)

In [ ]:
M = np.array([[0,1,2],[10,11,12]])
N = np.array([[12,11,10],[2,1,0]])
M + N                               # tout simplement

array([[12, 12, 12],
       [12, 12, 12]])

## **Produit d'une matrice par un réel**

In [ ]:
Lambda = -2.                        # flottant
M = np.array([[0,1,2],[10,11,12]])  # matrice d'entiers

Lambda * M                          # donc résultat : matrice de flottants


array([[ -0.,  -2.,  -4.],
       [-20., -22., -24.]])

## **Produit de deux matrices : la fonction *np.dot*** (pour deux matrices compatibles pour le produit, non commutatif, faut-il le rappeler ?)

In [ ]:
M = np.array([[0,1,2],[10,11,12]])
M

array([[ 0,  1,  2],
       [10, 11, 12]])

In [ ]:
N = np.transpose(np.array([[12,11,10],[2,1,0]]))
N

array([[12,  2],
       [11,  1],
       [10,  0]])

**remarque :** M*N fait le produit terme à terme des matrices M et N lorsquelles ont la même taille

In [ ]:
np.dot(M,N)

array([[ 31,   1],
       [361,  31]])

In [ ]:
np.dot(N,M)

array([[20, 34, 48],
       [10, 22, 34],
       [ 0, 10, 20]])

## **Carré et autres puissances d'une matrice carrée** 

Utiliser une boucle

(L'utilisation de M**2 pour M de type np.array donne la matrice des carrés des éléments de M, ce qui n'est pas la définition matricielle du carré de M...)

In [ ]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [ ]:
M**2

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
# puissance vraie d'une matrice carrée

n = 2
P = np.eye(2,2) # matrice identité 2x2
for k in range(n) :
    P = np.dot(P,M)
P

array([[ 7., 10.],
       [15., 22.]])

## **le type *np.matrix***

**remarque :** il existe dans numpy un type "***matrix***", non exigible, qui permet d'opérer encore plus simplement sur les matrices :


In [ ]:
M = np.matrix([[0,1,2],[10,11,12]])
M

matrix([[ 0,  1,  2],
        [10, 11, 12]])

In [ ]:
N = np.transpose(np.matrix([[12,11,10],[2,1,0]]))
N

matrix([[12,  2],
        [11,  1],
        [10,  0]])

In [ ]:
M @ N                       # produit de deux matrices numpy

matrix([[ 31,   1],
        [361,  31]])

In [ ]:
M = np.matrix([[1,2],[3,4]])
M**2                        # vrai carré de M

matrix([[ 7, 10],
        [15, 22]])

In [ ]:
M**(-1) # inverse de M, procédé non exigible, on privilégiera le procédé ci-après...

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

## **Puissance d'une matrice carrée et inverse d'une matrice carrée inversible : la fonction *np.linalg.matrix_power* et la fonction *np.linalg.inv***

(à connaître !)

In [ ]:
M = np.array([[1,2],[3,4]])
np.linalg.matrix_power(M,2)

array([[ 7, 10],
       [15, 22]])

In [ ]:
M = np.array([[1,2],[3,4]])
np.linalg.inv(M)            # inv figure dans le sous-module "linalg" (algèbre linéaire) de numpy

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## **Quelques matrices particuières pratiques et à connaître**

* **Identité**

In [ ]:
I = np.eye(3,3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* **Matrice nulle**

In [ ]:
 Z = np.zeros((3,3)) # Attention : il est indispensable de doubler les parenthèses !!!
 Z  

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

* **Matrice de 1**

In [ ]:
U = np.ones((3,3))
U

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* **Matrice diagonale**

In [ ]:
D = np.diag([1,2,3])
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

* **Matrice ligne régulièrement espacée entre deux bornes**

    (--> ressemble à "***range(n)***", mais avec des flottants)

In [ ]:
L = np.arange(1,3,0.25)             # vecteur ligne de 1 à 3 avec un pas de 0.25
                                    # observer que 1 est inclus et 3 exclu, comme toujours

# **3. Résolution de systèmes carrés**

## **3.1 Résolution par la méthode du pivot de Gauss**

La grande facilité à opérer sur les *arrays* de NumPy permet d'envisager assez simplement les opérations élémentaires du pivot de Gauss !

On commence par écrire le système matriciellement :

A.X = B

où A est la matrice carrée du système, X le vecteur colonne des inconnues et B le vecteur colonne du second membre.

On sait que l'on dispose de **trois opérations élémentaires** :

* **permutation : permuter deux lignes , $L_i \leftrightarrow L_j$**

        A[[i,j]] = A[[j,i]]

* **dilatation : multiplier une ligne par un réel , $L_i \leftarrow \lambda *L_i$**

        A[i] = Lambda * A[i]

* **transvection : ajouter à une ligne le produit d'une autre par un réel  , $L_i \leftarrow \ L_i + \alpha *L_j$**

        A[i] = A[i] + Alpha * A[j]

(https://www.codecogs.com/latex/eqneditor.php?lang=fr-fr)

*Faire agir ces opérations sur la matrice identité pour bien comprendre matriciellement les effets recherchés.*

**1<sup>ère</sup> étape : la "descente"**

On commence par triangulariser la matrice, ça, c'est toujours possible.

**2<sup>ème</sup> étape : la "remontée"**

Puis, s'il n'y a pas de 0 sur la diagonale, c'est que la matrice est inversible, 

on finalise donc la diagonalisation de la matrice.

**3<sup>ème</sup> étape : la "remontée"**

La résolution finale du système vient alors rapidement, puisque sa matrice a été diagonalisée.

### **Remarque sur le choix du pivot**

Mathématiquement, tous les pivots non nuls se valent, mais dès que l'on introduit des valeurs approchées, ce qui est toujours le cas quand on fait tourner un programme sur une machine...il arrive que les systèmes soient "mal dimensionnés", c'est-à-dire que des arrondis successifs pourtant précis entraînent une grosse imprécision sur la solution finale.

Voir un exemple ici : 

https://info-llg.fr/commun-mpsi/pdf/10.pivot.pdf 

Pour éviter ces effets cataclysmiques, on choisit une variante du pivot de Gauss, dans lequel on fait en sorte de pivoter sur le plus grand des pivots possibles.

Commenter le programme suivant :

In [ ]:
def recherche_pivot(A, b, j):
    p = j
    for i in range(j+1, A.shape[0]):
        if abs(A[i, j]) > abs(A[p, j]):
            p = i
    if p != j:
        b[[p, j]] = b[[j, p]]
        A[[p, j]] = A[[j, p]]

def elimination_bas(A, b, j):
    for i in range(j+1, A.shape[0]):
        b[i] = b[i] - (A[i, j] / A[j, j]) *b[j]
        A[i] = A[i] - (A[i, j] / A[j, j]) *A[j]

def descente(A, b):
    for j in range(A.shape[1] - 1):
        recherche_pivot(A, b, j)
        elimination_bas(A, b, j)

def elimination_haut(A, b, j):
    for i in range(j):
        b[i] = b[i] - (A[i, j] / A[j, j]) *b[j]

def remontee(A, b):
    for j in range(A.shape[1] - 1, 0, -1):
        elimination_haut(A, b, j)

def solve_diagonal(A, b):
    for k in range(b.shape[0]):
        b[k] = b[k] / A[k, k]
    return b

def gauss(A, b):
    U = A.copy()
    v = b.copy()
    descente(U, v)
    remontee(U, v)
    return solve_diagonal(U, v)

**1<sup>er</sup> exemple :**


In [ ]:
A = np.array([[1,1,1], [1,-2,1],[2,-1,1]], dtype=float)
A

array([[ 1.,  1.,  1.],
       [ 1., -2.,  1.],
       [ 2., -1.,  1.]])

In [ ]:
b = np.array([[1],[0],[2]], dtype=float)
b

array([[1.],
       [0.],
       [2.]])

In [ ]:
print('Solution approchée du système :')

gauss(A,b)

Solution approchée du système :


array([[ 1.66666667],
       [ 0.33333333],
       [-1.        ]])



**2<sup>ème</sup> exemple : (système mal dimensionné)**

In [ ]:
A = np.array([[0.003,59.14], [5.291,-6.13]], dtype=float)
A

array([[ 3.000e-03,  5.914e+01],
       [ 5.291e+00, -6.130e+00]])

In [ ]:
b = np.array([[59.17],[46.78]], dtype=float)
b

array([[59.17],
       [46.78]])

In [ ]:
print('Solution approchée du système :')

gauss(A,b)

Solution approchée du système :


array([[10.],
       [ 1.]])

... Vérifier à la main...