<a href="https://colab.research.google.com/github/othoni-hub/ECG1/blob/main/Ch4_TD_Corrig%C3%A9s.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ch4 - TD - Corrigés**

<img src="https://drive.google.com/uc?id=12Wo3LubGGT4qOvYFAuLP4CyCuwjKNVuk" width="230" height="150" align = "right"/>




**O.Thöni - Lycée Saint-Charles Sainte Croix - LE MANS**


## **Ex1 : graphe des diviseurs**

*source : "Mathématiques appliquées et Informatique", Bruno Grebille, Éd. Studyrama*
### **1°) Constitution du graphe**

In [ ]:
E = set(range(7))
#E = set((0,1,2,4,8,16,32))
E

{0, 1, 2, 3, 4, 5, 6}

In [ ]:
def divise(i,j) :
    '''fonction qui reçoit deux entiers i et j
    et renvoie 1 si i divise j et 0 sinon'''
    if i == 0 :
        return False
    else :
        if j%i == 0 :
            return True
        else :
            return False

In [ ]:
V = set((i,j) for i in E for j in E if divise(i,j)) # graphe par compréhension
                                                    # on a retiré 0 des i possibles, pour ne pas avoir de division par 0 ;)
V

{(1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 0),
 (2, 2),
 (2, 4),
 (2, 6),
 (3, 0),
 (3, 3),
 (3, 6),
 (4, 0),
 (4, 4),
 (5, 0),
 (5, 5),
 (6, 0),
 (6, 6)}

### **2°) Matrice d'adjacence**

In [ ]:
import numpy as np

def matrice_adjacence(Ens) :
    '''Fonction qui reçoit un ensemble d'entiers Ens
    et qui renvoie la matrice d'adjacence A du graphe des diviseurs'''
    l = len(Ens)
    A = np.zeros((l,l),dtype=int)# On crée la matrice à la bonne dimension
    for i in Ens:
        for j in Ens: # on parcourt la matrice
            if divise(i,j) :      # si le n° de ligne divise le n° de colonne, on met un 1
                A[i,j] = 1
    return A

A = matrice_adjacence(E)
A

array([[0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 1, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1]])



<img src="https://drive.google.com/uc?id=1R2skeFWCtZqyDiq4XKXwFanUP4sFzJxx" width="550" height="350" />

**outil de tracé :**

https://wims.univ-cotedazur.fr/wims/fr_tool~geometry~graphviz.fr.html

### **3°) Degré des sommets**
Dans un graphe orienté, le **degré** d'un sommet est le nombre d'arcs qui en partent ou y arrivent (les boucles comptant double).

In [ ]:
def degre(E) :
    ''' Fonction qui reçoit un ensemble, 
    calcule la matrice d'adjacence du graphe des diviseurs dans cet ensemble
    renvoie, grâce à un procédé matriciel, un vecteur colonne égal aux degrés entrant, sortant, total de chaque sommet'''
    L = len(E)
    A = np.matrix(matrice_adjacence(E), dtype = int) # par défaut, zeros et ones renvoient des matrices de flottants, on convertit en entier
                                                     # penser à doubler les parethèses derrière zeros et ones
    U = np.matrix(np.ones((L,1), dtype = int)) # matrice de 1, à L ligne et 1 colonne
    # @ désigne le produit matriciel pour les variables de type  np.matrix
    De = A @ U      # A @ U compte le nombre d'arcs sortant de chaque noeud (c'est-à-dire le nombre de multiples)
    # A.T est la matrice transposée de la matrice A
    Ds = A.T @ U    # A.T @ U compte le nombre d'arcs entrant dans chaque sommet (c'est-à-dire le nombre de diviseurs) 
    D = De + Ds                   
    return De,Ds,D

In [ ]:
De,Ds,D = degre(E)
print("Degrés sortant (c'est-à-dire nombre de diviseurs)")
Ds

Degrés sortant (c'est-à-dire nombre de diviseurs)


matrix([[6],
        [1],
        [2],
        [2],
        [3],
        [2],
        [4]])

In [ ]:
def degre0(E) :
    ''' Fonction qui reçoit un ensemble, 
    calcule la matrice d'adjacence du graphe des diviseurs dans cet ensemble
    renvoie, grâce à un procédé algorithmique, des matrices-colonnes égales aux degrés entrant, sortant, total de chaque sommet'''
    L = len(E)
    A = np.matrix(matrice_adjacence(E))
    De = np.matrix(np.zeros((L,1), dtype = int))
    Ds = np.matrix(np.zeros((L,1), dtype = int))
    for i in range(L):
        for j in range(L) :
            De[i] = De[i] + A[i,j]
            Ds[i] = Ds[i] + A[j,i]
    D = De + Ds
    return De, Ds, D


In [ ]:
De,Ds,D = degre0(E)
print("Degrés sortant (c'est-à-dire nombre de diviseurs)")
Ds

Degrés sortant (c'est-à-dire nombre de diviseurs)


matrix([[6],
        [1],
        [2],
        [2],
        [3],
        [2],
        [4]])

In [ ]:
def nb_chemins(A,l,i,j) :
    '''Fonction qui reçoit  * une matrice carrée A, matrice d'adjacence d'un graphe
                            * 3 entiers l, i et j
    et qui renvoie le nombre de chemins de longueur l reliant i à j'''
    A = np.matrix(A)
    pA = A**l
    n = pA[i,j]
    return n, pA

In [ ]:
l = 3
i = 1
j = 6


n, pA = nb_chemins(A, l, i, j)
print(pA)
print('Il y a ', n, ' chemins de longueur ', l , ' reliant ', i , ' à ', j )

[[ 0  0  0  0  0  0  0]
 [14  1  3  3  6  3  9]
 [ 5  0  1  0  3  0  3]
 [ 3  0  0  1  0  0  3]
 [ 1  0  0  0  1  0  0]
 [ 1  0  0  0  0  1  0]
 [ 1  0  0  0  0  0  1]]
Il y a  9  chemins de longueur  3  reliant  1  à  6


### **4°) connexité ?**

In [ ]:
def connexe(A) :
    '''Fonction qui reçoit la matrice d'adjacence d'un graphe 
    et qui renvoie la matrice somme des puissances de A (jusqu'à sa taille - 1)
    et la valeur "vrai" si le graphe est connexe, "faux" sinon'''
    l,L= np.shape(A)
    S = np.matrix(np.eye(L), dtype = int)
    for p in range(1,L) : 
        S = S + A**p # S est la matrice contenant la somme des puissances de A de 0 à L-1
    return S, 0 not in S # Si 0 n'est dans la matrice S, A est fortement connexe

In [ ]:
S, boo = connexe(A)
print(S)
print(boo)

[[1 0 0 0 0 0 0]
 [6 7 6 6 6 6 6]
 [6 0 7 0 6 0 6]
 [6 0 0 7 0 0 6]
 [6 0 0 0 7 0 0]
 [6 0 0 0 0 7 0]
 [6 0 0 0 0 0 7]]
False


## **Ex 2 :** 


<img src="https://drive.google.com/uc?id=1BoXid2oLeRtrUrZetpMB8J8qXlChlScn" width="550" height="350" />

### **1°) Matrice d'adjacence et caractéristiques du graphe**

* noms de sommets ("*Vertices*")

In [ ]:
V = ["A","B","C","D","E","F","G"]
V

['A', 'B', 'C', 'D', 'E', 'F', 'G']

* Matrice d'adjacence

In [ ]:
# Matrice d'ajacence
A = np.matrix([
[0,1,0,0,1,0,0,0],
[1,0,1,0,1,1,0,0],
[0,1,0,1,0,1,1,0],
[0,0,1,0,0,0,1,0],
[1,1,0,0,0,1,0,1],
[0,1,1,0,1,0,1,1],
[0,0,1,1,0,1,0,0],
[0,0,0,0,1,1,0,0]])
l,L = np.shape(A)
A

matrix([[0, 1, 0, 0, 1, 0, 0, 0],
        [1, 0, 1, 0, 1, 1, 0, 0],
        [0, 1, 0, 1, 0, 1, 1, 0],
        [0, 0, 1, 0, 0, 0, 1, 0],
        [1, 1, 0, 0, 0, 1, 0, 1],
        [0, 1, 1, 0, 1, 0, 1, 1],
        [0, 0, 1, 1, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0]])

* connexité

In [ ]:
S, boo = connexe(A) # on recycle la fonction "connexe" de l'Ex1
print(S)
print(boo)

[[ 557 1029  927  441  958 1167  711  607]
 [1029 1862 1759  858 1747 2203 1323 1095]
 [ 927 1759 1667  856 1589 2063 1299 1019]
 [ 441  858  856  433  780 1005  670  497]
 [ 958 1747 1589  780 1613 2029 1212 1030]
 [1167 2203 2063 1005 2029 2527 1598 1294]
 [ 711 1323 1299  670 1212 1598  995  766]
 [ 607 1095 1019  497 1030 1294  766  646]]
True


* complétude

In [ ]:
def complet(A) :
    '''Fonction qui reçoit la matrice d'adjacence d'un graphe et renvoie vrai s'il est complet'''
    l,L = np.shape(A)
    if 0 not in (A + np.eye(L)) : # les 0 sur la diagonale, c'est-à-dire l'absence de boucles, 
                                # n'empêchent pas un graphe d'être complet
        return True
    else :
        return False


In [ ]:
complet(A)

False

### **2°) Distances dans un graphe**
- On appelle **distance** entre deux sommets la longueur du plus court chemin qui les joint.
- L’**excentricité** d’un sommet est la plus grande des distances qui le joint aux autres sommets
- Le **diamètre** d’un graphe est la plus grande des excentricités de ses sommets.
- Le **rayon** d’un graphe est la plus petite des excentricités et les **centres** sont les sommets ayant cette excentricité minimale.

* **Calcul de la matrice des distances entre les sommets**

S'il existe un chemin de longueur L entre deux sommets, alors qu'il n'existait pas de chemin de longueur L-1, c'est que la distance entre ces deux sommets vaut L.


In [ ]:
def matrice_des_distances(A) :
    r,c = np.shape(A)
    M = np.zeros((r,c), dtype = int) # penser aux doubles parenthèses pour "zeros"
    M = (A != 0)*1 # gère le cas d'un graphe pondéré

    P = np.copy(A)
    
    for p in range(2,r) :
        PA = P @ A # on calcule la puissance suivante de A
        for i in range(r):
            for j in range(c): # gère le cas des graphes orientés, sinon, on pourrait s'occuper uniquement d'une demi-matrice
                if i!=j :           # hors de la diagonale
                    if PA[i,j] != 0 and P[i,j] == 0 : # un élément de la puissance de A est non nul 
                                                      # alors qu'il l'était à la puissance précédente
                        M[i,j] = p
        P = np.copy(PA)
    return np.matrix(M)

In [ ]:
M = matrice_des_distances(A)
M

matrix([[0, 1, 2, 3, 1, 2, 3, 2],
        [1, 0, 1, 2, 1, 1, 2, 2],
        [2, 1, 0, 1, 2, 1, 1, 2],
        [3, 2, 1, 0, 3, 2, 1, 3],
        [1, 1, 2, 3, 0, 1, 2, 1],
        [2, 1, 1, 2, 1, 0, 1, 1],
        [3, 2, 1, 1, 2, 1, 0, 2],
        [2, 2, 2, 3, 1, 1, 2, 0]])

In [ ]:
i = 3
j = 0
print(V[i], 'est à la distance', M[i,j], 'de', V[j])
print( '{} est à la distance {} de {}'.format( V[i], M[i,j], V[j]))

D est à la distance 3 de A
D est à la distance 3 de A


* excentricité

In [ ]:
exc = np.max(M, axis = 1)   # axis = 1 indique que l'on met en colonne (axis = 1)
                            # les résultats de la recherche du max de chaque ligne de M
exc

matrix([[3],
        [2],
        [2],
        [3],
        [3],
        [2],
        [3],
        [3]])

* diamètre du graphe

In [ ]:
diam = np.max(M)
diam

3

* rayon du graphe

In [ ]:
ray = np.min(exc)
ray

2

* centres

In [ ]:
exc[2]

matrix([[2]])

In [ ]:
centres = set([V[i] for i in range(L) if exc[i] == ray])
centres

{'B', 'C', 'F'}

### **3°) Graphe eulérien**


* graphe eulérien, semi-eulérien

**Théorème : un graphe est eulérien si et seulement s'il est connexe et que tous ses sommets sotn de degré pair.**

**Théorème : Un graphe comporte un nombre pair de sommets de degré impair..**

Un graphe est semi-eulérien s'il ne comporte que deux sommets de degré impair. Il suffit alors de relier ces deux sommets pour obtenir un graphe eulérien

In [ ]:
# Graphe eulérien
# Rappel : un graphe est eulérien si et seulement si il est connexe et tous ses sommets sont de degré pair

def degre_mat(A) :
    ''' Fonction qui reçoit la matrice A d'adjacence d'un graphe 
    et renvoie un vecteur colonne égal aux degrés de chaque sommet'''
    l,L = np.shape(A)
    U = np.matrix(np.ones((L,1), dtype = int)) # matrice de 1, à L ligne et 1 colonne
    # @ désigne le produit matriciel pour les variables de type  np.matrix
    D = A @ U      # A @ U compte le nombre d'arête de chaque noeud 
    return D

In [ ]:
degre_mat(A)

matrix([[2],
        [4],
        [4],
        [2],
        [4],
        [5],
        [3],
        [2]])

In [ ]:
parite_sommets = degre_mat(A)%2 # on teste si les sommets sont de degré pair
parite_sommets

matrix([[0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0]])

In [ ]:
int(sum(degre_mat(A)%2)) # nombre de sommets de degré impair

2

In [ ]:
def eulerien(A):
    '''Fonction qui reçoit la matrice d'adjacence d'un graphe 
    et retourne une chaîne indiquant si ce graphe est eulérien, semi-eulérien, ou non'''
    S, boo = connexe(A)
    rep = "non eulérien"
    if boo == True : # Le graphe est connexe
        if sum(degre_mat(A)%2) == 0 :# tous les sommets sont de degré pair 
            rep = "eulérien" # Le graphe est eulérien
        elif sum(degre_mat(A)%2) == 2 : #Deux sommets de degré impair seulement
            rep = "semi-eulérien"
        
    return rep


In [ ]:
eulerien(A)

'semi-eulérien'

* Liaison des sommets impairs d'un graphe semi-eulérien

In [ ]:
liste_sommets_impairs = [i for i in range(L) if parite_sommets[i] == 1  ]
liste_sommets_impairs

[5, 6]

In [ ]:
if eulerien(A) =="semi-eulérien" :
    liste_sommets_impairs = [i for i in range(L) if parite_sommets[i] == 1  ]
    print("Le graphe est semi-eulérien, pour le rendre eulérien, relier les sommets : ", V[liste_sommets_impairs[0]], " et ", V[liste_sommets_impairs[1]])

Le graphe est semi-eulérien, pour le rendre eulérien, relier les sommets :  F  et  G


## **Ex 4 : réseaux sociaux**



In [ ]:
import numpy as np

M = np.matrix([
    [0,0,1,1,0,0,1],
    [0,0,0,0,1,1,0],
    [1,0,0,1,0,0,0],
    [1,0,1,0,0,0,1],
    [0,1,0,0,0,1,0],
    [0,1,0,0,1,0,0],
    [1,0,0,1,0,0,0]])
M

matrix([[0, 0, 1, 1, 0, 0, 1],
        [0, 0, 0, 0, 1, 1, 0],
        [1, 0, 0, 1, 0, 0, 0],
        [1, 0, 1, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 1, 0, 0],
        [1, 0, 0, 1, 0, 0, 0]])

In [ ]:
N = np.matrix([
    [0,0,1,0,0,0,0],
    [0,0,0,0,1,1,1],
    [1,0,0,1,0,1,1],
    [1,0,0,0,0,0,1],
    [0,0,0,1,0,1,1],
    [0,0,0,0,1,0,1],
    [1,0,0,0,0,0,0]])
N

matrix([[0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 0, 1, 1],
        [1, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0, 1, 1],
        [0, 0, 0, 0, 1, 0, 1],
        [1, 0, 0, 0, 0, 0, 0]])